# Generated by Django 5.1.7 on 2025-03-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_model1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
    ]
